### ISSUE TITLE
Wiki-DB 

### ISSUE THREAD

**Issue by dndimitri** [YueLiu/NeuralTripleTranslation#1]
The Wiki-DB link doesn't work (Data Section).

**Comment by dndimitri** [comment]
> @dndimitri were you able to get the data??
> @YueLiu please help with data.
> 
> Thanks

**Comment by YueLiu** [comment]
Hi, thanks for the notification, I have fixed the link regarding to the wiki-db text.

**Comment by YueLiu** [comment]
> The Wiki-DB link doesn't work (Data Section).

**Comment by dndimitri** [comment]
Thank you for your response. Everythink is fine !! Good work !!
